### ISSUE TITLE
Bug Report in Mobile Version of Thingsboard Professional Edition

### ISSUE THREAD

**Issue by Anderson-Andre-P** [thingsboard/flutter_thingsboard_pe_app#49]
## Description
Dear ThingsBoard Community Team,

I hope this message finds you all well. I'm reaching out to report a specific issue I encountered when trying to run my Flutter app with the latest version of ThingsBoard PE (1.0.7) on Android devices with API 21-30. works as expected on APIs 31 and 33.

## Problem Details:

Unexpected behavior occurs when trying to load dashboards from ThingsBoard PE on devices with API 21, 24, 29 and 30.

The app works as expected on APIs 31 and 33.

To provide visual evidence of the problem, I simultaneously emulated two devices: one with API 30 and the other with API 33. The attached image illustrates the error I am experiencing.

## build.gradle configuration

```gradle
android {
    compileSdkVersion 33

    defaultConfig {
        applicationId "org.thingsboard.pe.app"
        minSdkVersion 24
        targetSdkVersion 33
        ...
    }
}
```

## Application Modifications Before Identifying the Bug

- I incorporated the 'one_signal' package to make it easier to receive push notifications.

- I localized the app to my country's native language (Brazil, pt-BR).

## Solution Attempts

- I made efforts to update the flutter packages in the pubspec.yaml file, however, this did not bring significant changes in behavior.

- I also tried downloading the app again from the official repository. However, I found that even without any modifications, the application already has several problems, making it unfeasible to go in that direction.

I am reaching out to the community and their respected support team in hopes of finding a solution to this specific issue. Specifically, I'm looking for guidance to resolve the panel loading issue that is affecting Android devices with API 21-30 when using ThingsBoard PE version 1.0.7 in conjunction with the Flutter app.

This bug is negatively impacting as I can't launch an app that only works on modern phones. Thank you in advance for your attention and support to resolve this issue as soon as possible.

Your expertise and assistance in resolving this issue would be greatly appreciated. Please do not hesitate to request additional information or clarification as needed. Thank you for your attention and support.

The official thingsboard PE support wouldn't help, so I only have you to ask for help...

## Example of bug

![dashboards](https://github.com/thingsboard/flutter_thingsboard_pe_app/assets/61363255/d745e14c-a4f0-49ab-be08-bfb6d6e1f171)

## pubspeck.yaml

```yaml
name: ie_tec_app
description: Flutter ThingsBoard Mobile Application

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.7

environment:
  sdk: ">=2.12.0 <3.10.0"

dependencies:
  flutter:
    sdk: flutter
  thingsboard_pe_client: 1.0.7
  intl: ^0.17.0
  flutter_secure_storage: ^6.0.0
  flutter_speed_dial: ^6.0.0
  cupertino_icons: ^1.0.2
  fluro: ^2.0.3
  flutter_svg: ^1.1.3
  auto_size_text: ^3.0.0-nullsafety.0
  infinite_scroll_pagination: ^3.0.1
  fading_edge_scrollview: ^3.0.0
  stream_transform: ^2.0.0
  flutter_inappwebview:
    git:
      url: https://github.com/rshrc/flutter_inappwebview
      ref: master
  #  flutter_downloader: ^1.6.0
  #  permission_handler: ^8.0.0+2
  #  path_provider: ^2.0.2
  url_launcher: ^6.0.3
  image_picker: ^0.8.0
  mime: ^1.0.0
  logger: ^1.0.0
  qr_code_scanner: ^1.0.0
  device_info_plus: ^4.1.2
  geolocator: ^9.0.1
  material_design_icons_flutter: ^7.0.7296
  package_info: ^2.0.2
  dart_jsonwebtoken: ^2.2.0
  crypto: ^3.0.1
  flutter_form_builder: ^7.0.0
  form_builder_validators: ^8.3.0
  uni_links: ^0.5.1
  flutter_html: ^3.0.0-alpha.5
  universal_html: ^2.0.8
  universal_platform: ^1.0.0+1
  preload_page_view: ^0.1.6
  flutter_localizations:
    sdk: flutter
  onesignal_flutter: ^3.5.0
  l10n_flutter: ^1.0.7
  intl_translation: ^0.18.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

dependency_overrides:
  intl: 0.18.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/ie_logo.png"
flutter_intl:
  enabled: true
```
